
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.sopware.services.demo.whiteboard;

import java.util.logging.Logger;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Dec 22 08:56:13 CET 2010
 * Generated source version: 2.3.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "WhiteboardProvider",
                      portName = "localhost",
                      targetNamespace = "http://services.sopware.org/demo/Whiteboard",
                      wsdlLocation = "file:/Users/dwolz/git/EasyB_In_Equinox_Testing/TsfSample/TsfWsdlSample/Whiteboard.wsdl",
                      endpointInterface = "org.sopware.services.demo.whiteboard.Whiteboard")
                      
public class WhiteboardImpl implements Whiteboard {

    private static final Logger LOG = Logger.getLogger(WhiteboardImpl.class.getName());

    /* (non-Javadoc)
     * @see org.sopware.services.demo.whiteboard.Whiteboard#read(org.sopware.services.demo.whiteboard.Read  parameters )*
     */
    public org.sopware.services.demo.whiteboard.AnyType read(Read parameters) throws ReadFaultMsg    { 
        LOG.info("Executing operation read");
        System.out.println(parameters);
        try {
            org.sopware.services.demo.whiteboard.AnyType _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ReadFaultMsg("read_faultMsg...");
    }

    /* (non-Javadoc)
     * @see org.sopware.services.demo.whiteboard.Whiteboard#echo(org.sopware.services.demo.whiteboard.AnyType  parameters )*
     */
    public org.sopware.services.demo.whiteboard.AnyType echo(AnyType parameters) { 
        LOG.info("Executing operation echo");
        System.out.println(parameters);
        try {
            org.sopware.services.demo.whiteboard.AnyType _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.sopware.services.demo.whiteboard.Whiteboard#write(java.lang.String  key ,)org.sopware.services.demo.whiteboard.AnyType  value )*
     */
    public void write(java.lang.String key,org.sopware.services.demo.whiteboard.AnyType value) { 
        LOG.info("Executing operation write");
        System.out.println(key);
        System.out.println(value);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
